### ISSUE TITLE
Front - Set up environment

### ISSUE THREAD

**Issue by tremorrisdev** [tremorris1999/speed-commerce#13]
## TODO:
- [x] Set up nginx in docker container
- [x] Set up nx workspace
- [x] Configure component library package
- [x] Set up vite config
- [x] Configure webapp package
- [ ] (potential) Configure utility library template package
- [x] Evaluate sass configuration or explore alternatives
- [ ] #15
- [x] Configure lighthouse

**Comment by tremorrisdev** [comment]
No lighthouse configuration needed yet. Will just use chrome devtools
